### ISSUE TITLE
Feature request: Automatically pull (and cache) the public key

### ISSUE THREAD

**Issue by jaredsmith** [asipto/secsipidx#3]
It would be nice if this would automatically pull (and perhaps cache, for a certain amount of time) the public key from the x5u URL, instead of having to manually do that part.

**Comment by miconda** [comment]
It was listed in To-Do for long time (https://github.com/asipto/secsipidx/blob/master/README.md#to-do), but I didn't get to it yet. Now that there is some interest, I will try to prioritise it.

**Comment by miconda** [comment]
I just pushed support for a basic caching mechanism of the public keys in local files. It can be activated by giving `-cache-dir /path/to/cachedir` cli parameter, how long the cached value is considered valid can be controlled with `-cache-expire`.

The c library exports now:

```c
int SecSIPIDSetFileCacheOptions(char* dirPath, int expireVal);
```

which can be used to set the two values (the cache dir activates the caching mechanism). The name of the file in the cache directory is created from URL replacing first `://` with `_` and then the rest of `/` also with `_` -- I went this way instead of hashing (or encoding) the url to be human readable. Last modified time of the file is used to determine when the value is considered expired.

Kamailio module was also enhanced with two new parameters to set the cache dir and expire values.

There is no locking/synchronization on accessing (read/write) cache files for the moment, this can be done externally, for example with kamailio by using `cfgutils` module:

```c
$var(url) = $(hdr(Identity){s.rmws}{param.value,info}{s.unbracket});
lock("$var(url)");
if(secsipid_check_identity("")) { ... }
unlock("$var(url)");
```

I haven't done any testing yet, feedback would be appreciated.

The plan is to add a (more scalable) caching alternative by using a key-value storage system, considering Redis right now, so the management of the cache can also be done easier/programatically by other tools externally. If you have other suggestions here, let me know.

**Comment by jaredsmith** [comment]
That sounds great -- I'd be perfectly happy with using Redis as a back-end storage cache.

Any thoughts on having this library also download the certificate (if it doesn't find a copy in the cache)?

**Comment by miconda** [comment]
That's how is supposed to work: download the certificate if no corresponding (non-expired) file is found in cache dir and save it in the cache. Again, no real testing done yet, if you find any problem, report it and I will look into it.

**Comment by steve-kaufman** [comment]
This behavior is now tested in PR #18

**Comment by miconda** [comment]
Closing as it is implemented and tested, according to above comments.
